name: CI-Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Deployment:

    runs-on: self-hosted
  

    steps:
    - uses: actions/checkout@v3
    - name: docker action
      run: |
        sudo docker build .
        git clone https://github.com/HarshitAwasthi99/sonarqube-maven.git
        cd sonarqube
        mvn package
        
  
